export const ADD_TIMER_TO_QUEUE = 'ADD_TIMER_TO_QUEUE';
export const REMOVE_TIMER_FROM_QUEUE = 'REMOVE_TIMER_FROM_QUEUE';
export const ADD_CURRENT_LOG = 'ADD_CURRENT_LOG';
export const ADD_TIME_PRESSED_BUTTON = 'ADD_TIME_PRESSED_BUTTON';
export const CLEAR_LOGS = 'CLEAR_LOGS';